// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_LXa2ae47d9i-gG6_VDWOk9Oh12zk2CE',
    appId: '1:1043893614161:web:483c9de0508d976cf2aa70',
    messagingSenderId: '1043893614161',
    projectId: 'lost-and-found-99f74',
    authDomain: 'lost-and-found-99f74.firebaseapp.com',
    storageBucket: 'lost-and-found-99f74.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtpLOYFS99-47no0RRjHPy6MmiaQsei9Y',
    appId: '1:1043893614161:android:a40be87782d90791f2aa70',
    messagingSenderId: '1043893614161',
    projectId: 'lost-and-found-99f74',
    storageBucket: 'lost-and-found-99f74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAX9DFAtqihoUzmXOyczK9PNXQzk6v4CI',
    appId: '1:1043893614161:ios:e1dc475b9e339935f2aa70',
    messagingSenderId: '1043893614161',
    projectId: 'lost-and-found-99f74',
    storageBucket: 'lost-and-found-99f74.firebasestorage.app',
    iosBundleId: 'com.example.lostFoundApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAX9DFAtqihoUzmXOyczK9PNXQzk6v4CI',
    appId: '1:1043893614161:ios:e1dc475b9e339935f2aa70',
    messagingSenderId: '1043893614161',
    projectId: 'lost-and-found-99f74',
    storageBucket: 'lost-and-found-99f74.firebasestorage.app',
    iosBundleId: 'com.example.lostFoundApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_LXa2ae47d9i-gG6_VDWOk9Oh12zk2CE',
    appId: '1:1043893614161:web:5d0b9c595d06ef64f2aa70',
    messagingSenderId: '1043893614161',
    projectId: 'lost-and-found-99f74',
    authDomain: 'lost-and-found-99f74.firebaseapp.com',
    storageBucket: 'lost-and-found-99f74.firebasestorage.app',
  );
}
